build:
	docker-compose build
	# Alternatively, we can run `docker build -t craigbarrau/medrec-physicians`

up:
	docker-compose up -d

stop:
	docker-compose stop

push:
	docker tag physicians_app craigbarrau/medrec-physicians
	docker push craigbarrau/medrec-physicians
